# TinyRedis sample config

port 6379

# AOF persistence
appendonly yes
appendfilename appendonly.aof

# appendfsync supports: always, everysec, no
appendfsync everysec

# Replication. Uncomment to start as a replica.
# replicaof 127.0.0.1 6379
